### ISSUE TITLE
Container restarts every few seconds

### ISSUE THREAD

**Issue by pmirallesr** [duckietown/dt-duckiebot-interface#31]
Hello,

I've noticed that this container (duckietown/duckiebot-interface:master19, I assume it's this one) restarts frantically within my duckiebot. The reason is unknown, going through the logs revealed the following 2 red error messages:

> [ERROR] [1588690310.544135661]: Couldn't open joystick /dev/input/js0. Will retry every second.

> ================================================================================REQUIRED process [mobyduck/camera_node-3] has died!
> process has died [pid 103, exit code 1, cmd /home/duckiebot-interface/catkin_ws/src/camera_driver/src/camera_node_sequence.py __name:=camera_node __log:=/root/.ros/log/f1807ce8-8edf-11ea-8ad8-b827ebc67da2/mobyduck-camera_node-3.log].
> log file: /root/.ros/log/f1807ce8-8edf-11ea-8ad8-b827ebc67da2/mobyduck-camera_node-3*.log
> Initiating shutdown!
> ================================================================================
> 

I'm unsure of their meaning but I suspect they are related to why I cannot run the duckie's manual control

**Comment by pmirallesr** [comment]
This is the output of htop from within the duckie
![image](https://user-images.githubusercontent.com/52211742/81278880-9505e480-9056-11ea-9e7d-301fec883f31.png)

**Comment by pmirallesr** [comment]
And this is the docker ps -a output. You can see that the container started recently, it does that all the time but provides no exit/restart code

![image](https://user-images.githubusercontent.com/52211742/81279068-e4e4ab80-9056-11ea-944a-653db12024be.png)

**Comment by liampaull** [comment]
This was due to running instructions from the `DT19` book on a robot initialized with `daffy` configuration.
