### ISSUE TITLE
encoder resolution parameter

### ISSUE THREAD

**Issue by femust** [duckietown/dt-duckiebot-interface#60]
Hey, so I have a custom-built duckiebot, which is basically Duckiebot DB-19 but with a different type of motors [click](https://botland.store/dc-motors-with-gearbox-and-encoders/6287-micro-dc-geared-motor-wencoder-sj01-6v-160rpm-1201.html) in comparison to the default type of motors [click](https://dagurobot.en.made-in-china.com/product/edTJjYAcbEkF/China-Hall-Speed-Encoder-Motor-Gear-Box.html) it has different type of resolution. Basically it works and it counts the number of ticks, but since the resolution is different therefore the odometry results are quite different. In [those config files](https://github.com/duckietown/dt-duckiebot-interface/tree/905cbb08b5129624f69807d05f0ff58ab123d9cb/packages/wheel_encoder/config/wheel_encoder_node) there is a chance to change this resolution dynamically, but not sure where I could change this on the docker without rebuilding the image itself? Is there a chance to do rosparam with it?

**Comment by afdaniele** [comment]
# Description

This is definitely something we can do, I'm setting up a branch `daffy-encoder-calibration` that we will use to develop this.

The way this will work is similar to how we handle camera calibration. 

Encoders calibrations will be stored as `/data/config/calibrations/encoder/<SIDE>/<ROBOT_NAME>.yaml`, with `<SIDE> \in {'left', 'right'}`.

Given that this is an optional calibration, the node should be tolerant to missing calibration files and directories.
Unlike for the camera (and other) calibrations, the default calibration will NOT be stored in a `default.yaml` file, but in the node's configuration file inside the catkin package (the way it is setup now).

An encoder calibration file will have a smaller footprint compared to that of a current node configuration file.
In particular, the only parameter that can really be calibrated is the `resolution`.
An encoder calibration file will look like the following, 

```
resolution: 135
```

# Developers

- @afdaniele 
- @jasonhu5

**Comment by YoloAlien** [comment]
I have a problem with custom encoder resolution in novnc when testing activities from MOOC on edx. After changing resolution to the desired value from configuration files I have created on my robot I still have default value of 135 in novnc. Is it a bug or should I change something to update my resolution in novnc?
